### ISSUE TITLE
yarn 和 npm区别调查

### ISSUE THREAD

**Issue by jiu-z** [NATIVA-C/ctd#6]

**Comment by yc-har** [comment]
1、并行安装：yarn安装包会同时执行多个任务，npm 需等待上一个任务安装完成才能运行下一个任务
2、离线模式：如果你已经安装过一个包，用 yarn 再次安装会从缓存中获取，而 npm 会从网络下载
3、版本锁定：yarn 默认有一个 yarn.lock 文件锁定版本，保证环境统一，而 npm 默认从网络下载最新的最稳定的，版本锁定可以解决包之间版本不兼容问题，npm 也可以通过命令实现版本锁定
4、更简洁的输出：yarn 安装包时输出的信息较少，npm 输出信息冗余
![image](https://github.com/NATIVA-C/ctd/assets/64720585/1fc2ce17-c52c-4186-9e95-f48efa0b1482)
